services:
  bot:
    image: ghcr.io/andchch/local-tg-bot/bot:latest
    container_name: topbot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"